#!/usr/bin/env bash
set -euo pipefail

# Usage: ./run.sh

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SRCS="$DIR/main.cpp $DIR/particle.cpp $DIR/game.cpp $DIR/celestialBody.cpp"
OUT="$DIR/main"
ASSETS_DIR="$DIR/assets"
HEADER_OUT="$DIR/embedded_assets.h"

# 1. GENERATE HEADER FILE FROM IMAGES
# We use 'xxd' to convert binary images into C++ hex arrays
echo "Embedding assets into $HEADER_OUT..."

# Clear/Create the file
echo "// Auto-generated by run.sh" > "$HEADER_OUT"

# Function to embed a specific file
embed_file() {
    local file="$1"
    if [ -f "$ASSETS_DIR/$file" ]; then
        # xxd -i converts file to C array. 
        # We use sed to make sure the array is 'const' (optional but good practice)
        (cd "$DIR" && xxd -i "assets/$file") >> "$HEADER_OUT"
    else
        echo "Warning: Asset $file not found!"
    fi
}

# Embed specifically the files you mentioned
embed_file "arrow.png"
for i in {1..8}; do
    embed_file "planet$i.png"
done

echo "Assets embedded."

# 2. COMPILE
echo "Compiling $SRCS -> $OUT"

if command -v pkg-config >/dev/null 2>&1 && pkg-config --exists raylib; then
  echo "Using pkg-config to get raylib flags"
  PKG_CFLAGS=$(pkg-config --cflags raylib)
  PKG_LIBS=$(pkg-config --libs raylib)
  g++ -std=c++17 $PKG_CFLAGS $SRCS -o "$OUT" $PKG_LIBS
else
  echo "pkg-config or raylib not found; using fallback link flags"
  g++ -std=c++17 $SRCS -o "$OUT" -lraylib -lGL -lm -lpthread -ldl -lrt -lX11
fi

# 3. RUN
# Determine libdir for runtime
LIBDIR=""
if command -v pkg-config >/dev/null 2>&1 && pkg-config --exists raylib; then
  LIBDIR=$(pkg-config --variable=libdir raylib 2>/dev/null || true)
fi
LIBDIR=${LIBDIR:-/usr/local/lib}

export LD_LIBRARY_PATH="$LIBDIR:${LD_LIBRARY_PATH:-}"

echo "Running $OUT"
exec "$OUT"
